### ISSUE TITLE
feature importance logistic regression

### ISSUE THREAD

**Issue by antschum** [theislab/augurpy#34]
(Not sure if issues are intended to be used this way, but.)

I would like to add the feature importances for the random forest and logistic regression. In the case of the random forest I propose to use the build in function. For logistic regression there is no äquivalent on sklearn. Augur used standardized coefficients with Agresti method and linked this: https://think-lab.github.io/d/205/#3. 

I have not had time to fully dive into it but was wondering if @Zethson you know any other way or have preferences :)
(This is not integral to creating a cell type ranking so its not super urgent.)

**Comment by Zethson** [comment]
Sounds cool to me. I have no preferences or ideas.

**Comment by Zethson** [comment]
This is done, right?
